# Generated by Django 2.2.6 on 2020-07-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200710_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, upload_to='application/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post_vacancy',
            name='subjects',
            field=models.CharField(choices=[('BIO/PHY', 'BIO/PHY'), ('MATH/PHYC', 'MATH/PHYC'), ('KIS/FASIHI', 'KIS/FASIHI'), ('HIST/CRE', 'HIST/CRE'), ('ENG/LIT', 'ENG/LIT'), ('BIO/AGRIC', 'BIO/AGRIC'), ('MATH/BST', 'MATH/BST'), ('COMPUTER', 'COMPUTER')], max_length=15),
        ),
    ]
